# Generated by Django 3.1.5 on 2021-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210122_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='que',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
