# Generated by Django 3.1.5 on 2021-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210122_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='que',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
